Insert into Company values ( 'Emkay Entertainments', 'Nobel House, Regent Centre', 'Lothian' ), ( 'The Empire',  'Milton Keynes Leisure Plaza',  'Buckinghamshire' ),
                ( 'Asadul Ltd',  'Hophouse',  'Essex' ),
                ( 'Gargamel ltd',  '',  '' ),
                ( 'Ashley Mark Publishing Company',  '1-2 Vance Court',  'Tyne & Wear' ),
                ( 'MuchMoreMusic Studios',  'Unit 29',  'London' ),
                ( 'Victoria Music Ltd',  'Unit 215',  'London' ),
                ( 'Abacus Agent',  'Regent Street',  'London' ),
                ( 'Atomic',  '133 Longacre',  'London' ),
                ( 'Pyramid Posters',  'The Works',  'Leicester' ),
                ( 'Kingston Smith Financial Services Ltd',  '105 St Peter''s Street',  'Herts' ),
                ( 'Garrett Axford PR',  'Harbour House',  'West Sussex' ),
                ( 'Derek Boulton Management',  '76 Carlisle Mansions',  'London' ),
                ( 'Total Concept Management (TCM)',  'PO Box 128',  'West Yorks' ),
                ( 'Billy Russell Management',  'Binny Estate',  'Edinburgh' ),
                ( 'Stage Audio Services',  'Unit 2',  'Stourbridge' ),
                ( 'Windsong International',  'Heather Court',  'Kent' ),
                ( 'Vivante Music Ltd',  '32 The Netherlands',  'Surrey' ),
                ( 'Way to Blue',  'First Floor',  'London' ),
                ( 'Glasgow City Halls',  '32 Albion Street',  'Lanarkshire' ),
                ( 'The List',  '14 High St',  'Edinburgh' ),
                ( 'Wilkinson Turner King',  '10A London Road',  'Cheshire' ),
                ( 'GSC Solicitors',  '31-32 Ely Place',  'London' ),
                ( 'Vanessa Music Co',  '35 Tower Way',  'Devon' ),
                ( 'Regent Records',  'PO Box 528',  'West Midlands' ),
                ( 'BBC Radio Lancashire',  '20-26 Darwen St',  'Blackburn' ),
                ( 'The Citadel Arts Centre',  'Waterloo Street',  'Merseyside' ),
                ( 'Villa Audio Ltd',  'Baileys Yard',  'Essex' ),
                ( 'Astra travel',  '',  '' ),
                ( 'Idle Eyes Printshop',  '81 Sheen Court',  'Surrey' ),
                ( 'Miggins Music (UK)',  '33 Mandarin Place',  'Oxon' ),
                ( 'Magic 999',  'St Paul''s Square',  'Lancashire' ),
                ( 'Delga Group',  'Seaplane House, Riverside Est.',  'Kent' ),
                ( 'Zane Music',  '162 Castle Hill',  'Berkshire' ),
                ( 'Universal Music Operations',  'Chippenham Drive',  'Milton Keynes' ),
                ( 'Gotham Records',  'PO Box 6003',  'Birmingham' ),
                ( 'Timbuktu Music Ltd',  '99C Talbot Road',  'London' ),
                ( 'Online Music',  'Unit 18, Croydon House',  'Surrey' ),
                ( 'Irish Music Magazine',  '11 Clare St',  'Ireland' ),
                ( 'Savoy Records',  'PO Box 271',  'Surrey' ),
                ( 'Temple Studios',  '97A Kenilworth Road',  'Middlesex' ),
                ( 'Gravity Shack Studio',  'Unit 3 ',  'London' ),
                ( 'Dovehouse Records',  'Crabtree Cottage',  'Oxon' ),
                ( 'Citysounds Ltd',  '5 Kirby Street',  'London' ),
                ( 'Revolver Music Publishing',  '152 Goldthorn Hill',  'West Midlands' ),
                ( 'Jug Of Ale',  '43 Alcester Road',  'West Midlands' ),
                ( 'Isles FM 103',  'PO Box 333',  'Western Isles' ),
                ( 'Headscope',  'Headrest',  'East Sussex' ),
                ( 'Universal Music Ireland',  '9 Whitefriars',  'Ireland' ),
                ( 'Zander Exports',  '34 Sapcote Trading Centre',  'London' ),
                ( 'Midem (UK)',  'Walmar House',  'London' ),
                ( 'La Rocka Studios',  'Post Mark House',  'London' ),
                ( 'Warner Home DVD',  'Warner House',  'London' ),
                ( 'Music Room',  'The Old Library',  'London' ),
                ( 'Blue Planet',  '96 York Street',  'London' ),
                ( 'Dream 107.7FM',  'Cater House',  'Chelmsford' ),
                ( 'Moneypenny Agency',  'The Stables, Westwood House',  'East Yorks' ),
                ( 'Artsun',  '18 Sparkle Street',  'Manchester' ),
                ( 'Clyde 2',  'Clydebank Business Park',  'Glasgow' ),
                ( '9PR',  '65-69 White Lion Street',  'London' ),
                ( 'River Studio''s',  '3 Grange Yard',  'London' ),
                ( 'Start Entertainments Ltd',  '3 Warmair House',  'Middx' ),
                ( 'Vinyl Tap Mail Order Music',  '1 Minerva Works',  'West Yorkshire' ),
                ( 'Passion Music',  '20 Blyth  Rd',  'Middlesex' ),
                ( 'SuperVision Management',  'Zeppelin Building',  'London' ),
                ( 'Lite FM',  '2nd Floor',  'Peterborough' ),
                ( 'ISIS Duplicating Company',  'Sales & Production',  'Merseyside' ),
                ( 'Vanderbeek & Imrie Ltd',  '15 Marvig',  'Scotland' ),
                ( 'Glamorgan University',  'Student Union',  'Mid Glamorgan' ),
                ( 'Web User',  'IPC Media',  'London ' ),
                ( 'Farnborough Recreation Centre',  '1 Westmead',  'Hampshire' ),
                ( 'Robert Owens/Musical Directions',  '352A Kilburn Lane',  'London' ),
                ( 'Magick Eye Records',  'PO Box 3037',  'Berks' ),
                ( 'Alexandra Theatre',  'Station Street',  'West Midlands' ),
                ( 'Keda Records',  'The Sight And Sound Centre',  'Middlesex' ),
                ( 'Independiente Ltd',  'The Drill Hall',  'London' ),
                ( 'Shurwood Management',  'Tote Hill Cottage',  'West Sussex' ),
                ( 'Fury Records',  'PO Box 52',  'Kent' ),
                ( 'Northumbria University',  'Union Building',  'Newcastle upon Tyne' ),
                ( 'Pop Muzik',  'Haslemere',  'W. Sussex' ),
                ( 'Jonsongs Music',  '3 Farrers Place',  'Surrey' ),
                ( 'Hermana PR',  'Unit 244, Bon Marche Centre',  'London' ),
                ( 'Sugarcane Music',  '32 Blackmore Avenue',  'Middlesex' ),
                ( 'JFM Records',  '11 Alexander House',  'London' ),
                ( 'Black Market Records',  '25 D''Arblay Street',  'London' ),
                ( 'Float Your Boat Productions',  '5 Ralphs Retreat',  'Bucks' ),
                ( 'Creation Management',  '2 Berkley Grove',  'London' ),
                ( 'Bryter Music',  'Marlinspike Hall',  'suffolk' ),
                ( 'The Headline Agency',  '39 Churchfields',  'Ireland' ),
                ( 'MP Promotions',  '13 Greave',  'Cheshire' ),
                ( 'Modo Production Ltd',  'Ground Floor',  'London' ),
                ( 'Nomadic Music',  'Unit 18',  'London' ),
                ( 'Reverb Records Ltd',  'Reverb House',  'London' ),
                ( 'SIBC',  'Market Street',  'Lerwick' ),
                ( 'Marken Time Critical Express',  'Unit 2',  'Isleworth' ),
                ( '102.2 Smooth FM',  '26-27 Castlereagh Street',  'London' ),
                ( 'Chesterfield Arts Centre',  'Chesterfield College',  'Derbyshire' ),
                ( 'The National Indoor Arena',  'King Edward''s Road',  'West Midlands' ),
                ( 'Salisbury City Hall',  'Malthouse Lane',  'Wiltshire' ),
                ( 'Minder Music',  '',  '' );
